language: ruby
os: linux
dist: trusty
rvm:
- 2.4.1
install: gem install jekyll -v 3.8.0 && gem install jekyll-redirect-from && gem install
  s3_website
script: jekyll build
after_success:
- test $TRAVIS_BRANCH = "master" && s3_website push --config-dir=_config/production/
- test $TRAVIS_BRANCH = "staging" && s3_website push --config-dir=_config/staging/
branches:
  only:
  - master
  - staging
notifications:
  slack:
    secure: tORSt//ZJIxNhgn4zZV46LhZ48O+ddpF5tVUCrj07Ps/rkx+4lKoyja2G2DDGTEl6xXJlcJJnwh+f5qNu1Tr1KiycGtJJI9YO3vcWPXj9gz8Wl5SbdmRwPfoTDw0DIcBvP7f1Pb7ETmu/tsvzl7s52u/07hh6JokrPggurL9gk9ZOK3TSOX9iL0yiN8Z5dzi6GLekI2NSu+A/+btea/rPCVYTkRRZ7de8D1XlJroEyyJ2kAJWIfXcyUIBzmLbJLL44mtt459Rq7lz7fZBZRsZ2W67O6hcLlhmA3pQBpmEOOsbs7FiVeXUpTcUHBO7LRxAjnl4AEM7GI9tBX53Q4STbGMsSThU9uME0QlJ3ffRfSO+at9MCiTu+YQQpCKOmiAnfsytSp79DLFh3jULNDPskBgxM+pVoXM+4NcnIFTGTdfvcd5opPuapoNVVY9yKXwCAt+aeuBkWLkA6CWByYWnLghonXVcWyd/1AdGlV23SufcFZ+/g2ULM9YS/Oaz7vEyQ8S3DCO/Bww4Qf+U301fM/iWgiWj2noMz/mndIex2P+x0b2A3qsEDjkudh2AognuWKAqqxUrGXRFcXYWTyEbBxfz7sVp4pYwxRo9Cbft5ygh4EK+Heq2YCW9zwqXd+wlsBkqie+WB0RQLjsfw+V32YfLfEvgNbJD8bT7iL6qfo=
